### ISSUE TITLE
Query Endpoint Error

### ISSUE THREAD

**Issue by TaylorThiessen** [DareFox/HowLongToBeat-Proxy-API#17]
The query endpoint responds with the following error:

![screencapture-hltb-proxy-fly-dev-v1-query-2024-08-02-22_53_10](https://github.com/user-attachments/assets/b8334775-66f7-47f3-a8fa-f04bca7f6e48)

Example: https://hltb-proxy.fly.dev/v1/query?title=Edna

**Comment by DareFox** [comment]
Fixed in #18

**Comment by TaylorThiessen** [comment]
The error is back

**Comment by DareFox** [comment]
It seems that site changes search URL every day to prevent scraping. I'll will hotfix it for now, but in the future, I'll need to find a more automated approach for this problem

**Comment by ClassicSpeed** [comment]
I think it's error is back

**Comment by JunkiEDM** [comment]
Here are what fixes other repos made, in case it helps:
https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/pull/26
https://github.com/ckatzorke/howlongtobeat/pull/64

Looks like they're getting the search api key dynamically by matching `/"\/api\/search\/".concat\("([a-zA-Z0-9]+)"\)/g` on the base url (https://howlongtobeat.com/)

**Comment by DareFox** [comment]
> Here are what fixes other repos made, in case it helps: [ScrappyCocco/HowLongToBeat-PythonAPI#26](https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/pull/26) [ckatzorke/howlongtobeat#64](https://github.com/ckatzorke/howlongtobeat/pull/64)
> 
> Looks like they're getting the search api key dynamically by matching `/"\/api\/search\/".concat\("([a-zA-Z0-9]+)"\)/g` on the scripts on https://howlongtobeat.com/

Thanks for this info! Based on this I implemented auto scraping search key for proxy, now search should work even if HLTB will change key
