### ISSUE TITLE
 Can't find search key

### ISSUE THREAD

**Issue by olegsvs** [DareFox/HowLongToBeat-Proxy-API#24]
HTTP ERROR 500 java.lang.IllegalStateException: Can't find search key

**Comment by TaylorThiessen** [comment]
The search error message has changed to: 
HTTP ERROR 500 java.lang.IllegalStateException: Response is not 199 from HLTB server, can't get search key

The overview now also shows the following error message: 
HTTP ERROR 500 java.lang.NullPointerException

**Comment by DareFox** [comment]
Sorry for long inactivity, I forgot about GitHub for a month 😅 

This problem is fixed for now, but it will certainly return in future. HLTB banned my fly.io machine IP address from accessing their website, I fixed by changing IP. It's a cat and mouse game, they will eventually ban new IP too

**Comment by DareFox** [comment]
Error returned

**Comment by DareFox** [comment]
Fixed by #28

**Comment by marcus-crane** [comment]
It seems HLTB have broken the proxy again 😞
